vp2:
  extends:
    file: base-peer.yaml
    service: vp
  hostname: vp2
  environment:
    - CORE_PEER_ID=vp2
    - CORE_PEER_DISCOVERY_ROOTNODE=172.17.0.3:7051
    - CORE_SECURITY_ENROLLID=test_vp0
    - CORE_SECURITY_ENROLLSECRET=MwYpmSRjupbT
    - CORE_PEER_PKI_ECA_PADDR=membersrvc:7054
    - CORE_PEER_PKI_TCA_PADDR=membersrvc:7054
    - CORE_PEER_PKI_TLSCA_PADDR=membersrvc:7054
vp3:
  extends:
    file: base-peer.yaml
    service: vp
  hostname: vp3
  environment:
    - CORE_PEER_ID=nvp3
    - CORE_PEER_DISCOVERY_ROOTNODE=172.17.0.3:7051
    - CORE_PEER_VALIDATOR_ENABLED=false
    - CORE_SECURITY_ENROLLID=test_vp0
    - CORE_SECURITY_ENROLLSECRET=MwYpmSRjupbT
    - CORE_PEER_PKI_ECA_PADDR=172.17.0.2:7054
    - CORE_PEER_PKI_TCA_PADDR=172.17.0.2:7054
    - CORE_PEER_PKI_TLSCA_PADDR=172.17.0.2:7054
