membersrvc:
  image: yeasy/hyperledger-membersrvc:latest
  restart: unless-stopped
  ports:
    - "7054:7054"
  volumes: # docker.sock is mapped as the default CORE_VM_ENDPOINT
    - /var/run/docker.sock:/var/run/docker.sock
  command: membersrvc  # this repeats the default cmd to make sure

vp0: 
  extends: 
    file: base-peer.yaml 
    service: vp 
  hostname: vp0 
  environment: 
    - CORE_PEER_ID=vp0 
    - CORE_SECURITY_ENABLED=true 
    - CORE_SECURITY_ENROLLID=test_vp0 
    - CORE_SECURITY_ENROLLSECRET=MwYpmSRjupbT 
    - CORE_PEER_PKI_ECA_PADDR=membersrvc:7054 
    - CORE_PEER_PKI_TCA_PADDR=membersrvc:7054 
    - CORE_PEER_PKI_TLSCA_PADDR=membersrvc:7054 
  ports: 
    - "7050:7050" 
  links: 
    - membersrvc 
  command: sh -c "sleep 5; peer node start" 

vp1: 
  extends: 
    file: base-peer.yaml 
    service: vp 
  hostname: vp1 
  environment: 
    - CORE_PEER_ID=vp1 
    - CORE_PEER_DISCOVERY_ROOTNODE=vp0:7051 
    - CORE_SECURITY_ENROLLID=test_vp1 
    - CORE_SECURITY_ENROLLSECRET=5wgHK9qqYaPy 
    - CORE_PEER_PKI_ECA_PADDR=membersrvc:7054 
    - CORE_PEER_PKI_TCA_PADDR=membersrvc:7054 
    - CORE_PEER_PKI_TLSCA_PADDR=membersrvc:7054 
  links: 
    - membersrvc
    - vp0 
  command: sh -c "sleep 5; peer node start" 

vp2:
  extends:
    file: base-peer.yaml 
    service: vp
  hostname: vp2
  environment:
    - CORE_PEER_ID=vp2
    - CORE_SECURITY_ENABLED=true
    - CORE_PEER_DISCOVERY_ROOTNODE=vp0:7051
    - CORE_SECURITY_ENROLLID=test_vp2
    - CORE_SECURITY_ENROLLSECRET=vQelbRvja7cJ
    - CORE_PEER_PKI_ECA_PADDR=membersrvc:7054
    - CORE_PEER_PKI_TCA_PADDR=membersrvc:7054
    - CORE_PEER_PKI_TLSCA_PADDR=membersrvc:7054
  links:
    - membersrvc
    - vp0
  command: sh -c "sleep 5; peer node start"

# vp3 will be used for client interactive operations
# If you want to run fabric command on the host, then map 7051:7051 to host
# port, or use like `CORE_PEER_ADDRESS=172.17.0.2:7051` to specify peer addr.
vp3:
  extends:
    file: base-peer.yaml 
    service: vp
  hostname: vp3
  environment:
    - CORE_PEER_ID=vp3
    - CORE_SECURITY_ENABLED=true
    - CORE_PEER_DISCOVERY_ROOTNODE=vp0:7051
    - CORE_SECURITY_ENROLLID=test_vp3
    - CORE_SECURITY_ENROLLSECRET=9LKqKH5peurL
    - CORE_PEER_PKI_ECA_PADDR=membersrvc:7054
    - CORE_PEER_PKI_TCA_PADDR=membersrvc:7054
    - CORE_PEER_PKI_TLSCA_PADDR=membersrvc:7054
  links:
    - membersrvc
    - vp0
  command: sh -c "sleep 5; peer node start"


